version: '3.8'

services:
  sandbox:
    build: .
    volumes:
      - ./ssh:/home/devuser/.ssh:ro        # Read-only SSH keys
      - .:/workspace                       # Project source
      - /var/run/docker.sock:/var/run/docker.sock  # Docker CLI support
    working_dir: /workspace
    stdin_open: true
    tty: true
